---
- hosts: webservers
  user: ansible
  sudo: yes

  tasks:
  - name: Removing authorized keys from servers to revoke access
    action: file path=/etc/ssh/authorized_keys state=absent
    with_items: sshusers
    notify:
    - restart sshd

    handlers:
      - name: restart sshd
        service: name=sshd state=restarted
